### ISSUE TITLE
trim front of read for 50 bp

### ISSUE THREAD

**Issue by MichelMoser** [OpenGene/fastp#121]
Hi, 
I need to trim ONT reads for 50 bp from the start of each read. 

When i enter -f 50 option, i get following error back: 

```
ERROR: trim_front1 (--trim_front1) should be 0 ~ 30, suggest 0 ~ 4   
```
why is there a size limit to front trimming in fastp? 
Can it be removed? 
If you could point me to the relevant line in code, i can do it myself. 

Thanks and best regards, 
Michel

**Comment by MichelMoser** [comment]
changing line 134 of options.cpp should do the trick: 

  if(trim.front1 < 0 || trim.front1 > 30)

**Comment by sfchen** [comment]
`-f 50` means you discard the first 50 bp.

If you want only the first 50 bp, you should use `-b 50`

**Comment by zhixingfeng** [comment]
I got the same issue when use fastp on ONT data. Really love fastp as it is currently the fastest qc tools I could find, but it would perfect if the limit on trim.front1 could be discarded because we usually need to trim (discard) more than 30 in the front and 100 in the tail in long-read sequencing data. With these changes, people working with long-read data would definitely love it.

**Comment by isthisthat** [comment]
Ditto for me. Looking at long reads and would like to be able to trim without restriction. Can the error be changed to a warning? Thanks

**Comment by cirodri1** [comment]
Hello! I am running into the same problem, I also need to trim the first 50 bp but **_fastp_** does not let me. Do you have a solution for this?

**Comment by lynnyummy** [comment]
> options.cpp

Hi, I am trying to cut the 75bp reads in my PE150 data, but I don't understand of the meaning of change line 134? Could you please help to explain it more and what is the command? Thank you very much!
