### ISSUE TITLE
--cut_by_quality3/5 description is confusing

### ISSUE THREAD

**Issue by jdrnevich** [OpenGene/fastp#122]
We've been investigating how the --cut_by_quality trimming actually works. Two other issues (#24 and #65) had the same questions we have, and your answers to those were not detailed enough and neither is the description in the documentation. I'll try to spell out my confusion clearly...

The --cut_by_quality documentation references Trimmomatic and "sliding window" but it does not work the same way Trimmomatic's SLIDINGWINDOW option works, which is where I think a lot of the confusion comes from. Instead, --cut_by_quality works more similar to Trimmomatic's LEADING and TRAILING options, except it uses a minimum window size of 2 instead of single bases like L/T. Both  --cut_by_quality and L/T stop when reaching a window or base above the quality threshold. However, SLIDINGWINDOW slides down the entire sequence and can find low-quality windows in the middle of otherwise high-quality sequence and will discard the rest of the sequence starting at the low-quality window. This is why SLIDINGWINDOW should only be used after LEADING trimming, else the entire sequence that starts with a few low-quality bases would be lost.

At the very least, would you please change the documentation for --cut_by_quality to specifically state that it works similar to Trimmomatic's LEADING and TRAILING trimming, not SLIDINGWINDOW? I would also like to request that the minimum window size be allowed to be 1 so we could use it as a single base trimmer. Finally, a further enhancement would be to include an option that does work like SLIDINGWINDOW.

Thanks for an otherwise great software tool - we are really pleased with our testing overall and are close to switching to fastp for our production work!

**Comment by sfchen** [comment]
Thanks Jenny, I totally agree with you.

I will change the documentation and add the real sliding window algorithm.

Once the feature is implemented I will update this issue to ask you to take a test.

**Comment by jdrnevich** [comment]
Great! Let me know when the new feature is ready and we will test it. Thanks so much

**Comment by sfchen** [comment]
Could you please pull the latest code, build it and have a try?

**Comment by biozzq** [comment]
Hi @sfchen 

Great tool. However, after reading your updated document, just out of interesting, how to set the sliding window size for `-cut_by_quality3/5`?  In Trimmomatic, the `LEADING/TRAILING` just remove the low quality base by base if I am right. So, I do not know why did `fastp` use the same window size specified with `-W, --cut_window_size` for all three different operations you mentioned above.

Best,
Zhuqing

**Comment by sfchen** [comment]
I am considering allow `--cut_by_quality_aggressive` to use individual `window size` and `mean quality` settings. 

For example, add one option `--cut_window_size_aggressive`, if it's not set, it will be as same as `--cut_window_size`.

How do you think about it?

**Comment by biozzq** [comment]
Hi @sfchen 

In my mind, you can reduce the number of opinions and set the window size for `-cut_by_quality3/5` to be 1. On the other hand, we can set the quality liking following `-cut_by_quality3 10 -cut_by_quality5 10` which are same as `LEADING:10 TRAILING:10` in Trimmomatic. Thank you very much.

Best
Zhuqing

**Comment by sfchen** [comment]
1-window-size is already allowed. And the quality can be 1~30.

**Comment by biozzq** [comment]
Hi @sfchen 

No problem. How to set the opinions in `fastp` that will be same with `LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20` in the Trimmomatic. If you can provide us a example, it will be useful for us to understand the description of these parameters. Thank you very much.

Best,
Zhuqing

**Comment by sfchen** [comment]
I refactored the `cut by quality` features to make it more clear, now the document is:

fastp` supports per read sliding window cutting by evaluating the mean quality scores in the sliding window. From `v0.19.6`, `fastp` supports 3 different operations, and you enable one or all of them:
* `-5, --cut_front`             move a sliding window from front (5') to tail, drop the bases in the window if its mean quality is below cut_mean_quality, stop otherwise. Default is disabled. The leading N bases are also trimmed. Use `cut_front_window_size` to set the widnow size, and `cut_front_mean_quality` to set the mean quality threshold. If the window size is 1, this is similar as the Trimmomatic `LEADING` method.
* `-3, --cut_tail`              move a sliding window from tail (3') to front, drop the bases in the window if its mean quality is below cut_mean_quality, stop otherwise. Default is disabled. The trailing N bases are also trimmed. Use `cut_tail_window_size` to set the widnow size, and `cut_tail_mean_quality` to set the mean quality threshold. If the window size is 1, this is similar as the Trimmomatic `TRAILING` method.
* `-r, --cut_right`             move a sliding window from front to tail, if meet one window with mean quality < threshold, drop the bases in the window and the right part, and then stop. Use `cut_right_window_size` to set the widnow size, and `cut_right_mean_quality` to set the mean quality threshold.  This is similar as the Trimmomatic `SLIDINGWINDOW` method.


***WARNING: all these three operations will interfere deduplication for SE data, and `--cut_front` or `--cut_right` may also interfere deduplication for PE data. The deduplication algorithms rely on the exact matchment of coordination regions of the grouped reads/pairs.***

If `--cut_right` is enabled, then there is no need to enable `--cut_tail`, since the former is more aggressive. If `--cut_right` is enabled together with `--cut_front`, `--cut_front` will be performed first before `--cut_right` to avoid dropping whole reads due to the low quality starting bases.

Please be noted that `--cut_front` will interfere deduplication for both PE/SE data, and `--cut_tail` will interfere deduplication for SE data, since the deduplication algorithms rely on the exact matchment of coordination regions of the grouped reads/pairs.

If you don't set window size and mean quality threshold for these function respectively, `fastp` will use the values from `-W, --cut_window_size` and `-M, --cut_mean_quality `

**Comment by sfchen** [comment]
> Hi @sfchen
> 
> No problem. How to set the opinions in `fastp` that will be same with `LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20` in the Trimmomatic. If you can provide us a example, it will be useful for us to understand the description of these parameters. Thank you very much.
> 
> Best,
> Zhuqing

With the latest version of fastp, you can use following options to do the same as `LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20` in the Trimmomatic:
```
--cut_front --cut_front_window_size=1 --cut_front_mean_quality=3 --cut_tail --cut_tail_window_size=1  --cut_tail_mean_quality=3 --cut_right  --cut_right_window_size=4 --cut_right_mean_quality=20
```

**Comment by sfchen** [comment]
> Hi @sfchen
> 
> Thank you very much.
> 
> Best,
> Zhuqing

Would you please have a test with the new version, and update this issue? You can compile it from source, or download it from the latest prebuilt.

**Comment by biozzq** [comment]
I found some different (Trimmomatic kept one more base at the end of reads than fastp) between `fastp` and `Trimmomatic` when using the same filter threshold. I attached the file and commands I used.
`java -jar trimmomatic-0.38.jar PE -threads 2 -trimlog test.log test1.fq test2.fq test_1.fq test_1.single.fastq test_2.fq test_2.single.fastq LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:40 TOPHRED33`
`fastp -i test1.fq -I test2.fq.gz -o test.R1.fq -O test.R2.fq --cut_front --cut_front_window_size=1 --cut_front_mean_quality=3 --cut_tail --cut_tail_window_size=1 --cut_tail_mean_quality=3 --cut_right --cut_right_window_size=4 --cut_right_mean_quality=20`
[test.zip](https://github.com/OpenGene/fastp/files/2716456/test.zip)

**Comment by sfchen** [comment]
Thanks!

Besides `Trimmomatic kept one more base at the end of reads than fastp`, is there any other obvious difference?

**Comment by biozzq** [comment]
Hi @sfchen ，

Sorry, I just used one paired end reads to have a test. In this demo, I just found the little difference I mentioned above. Maybe `trimns`, `trimns_window_size`, and `trimns_mean_quality`?

Best
Zhuqing

**Comment by jdrnevich** [comment]
Looks like lots of progress has been made! I'm on an extended holiday now and will check it out when I get back to work next week.
Happy New Year,
Jenny

**Comment by sfchen** [comment]
> Hi @sfchen ，
> 
> Sorry, I just used one paired end reads to have a test. In this demo, I just found the little difference I mentioned above. Maybe `trimns`, `trimns_window_size`, and `trimns_mean_quality`?
> 
> Best
> Zhuqing

I just submitted a revision to keep the good bases in the tails of reads after cutting

**Comment by Zjianglin** [comment]
Hi @sfchen ,
     I want to perform `per read cutting by quality score`  and `deduplication ` by `fastp`. However, your document said that ```all these three operations will interfere deduplication for SE data, and --cut_front or --cut_right may also interfere deduplication for PE data. The deduplication algorithms rely on the exact matchment of coordination regions of the grouped reads/pairs.```. I'm wondering that whether I have to run two  passes to  achieve my goals or any better suggestion you can give me? 
     Thank you.

**Comment by sfchen** [comment]
> Hi @sfchen ,
> I want to perform `per read cutting by quality score` and `deduplication ` by `fastp`. However, your document said that `all these three operations will interfere deduplication for SE data, and --cut_front or --cut_right may also interfere deduplication for PE data. The deduplication algorithms rely on the exact matchment of coordination regions of the grouped reads/pairs.`. I'm wondering that whether I have to run two passes to achieve my goals or any better suggestion you can give me?
> Thank you.

Can you file an individual issue? I am closing this issue.
