### ISSUE TITLE
Default options not working

### ISSUE THREAD

**Issue by flashton2003** [OpenGene/fastp#154]
I'm trimming some data from ENA with fastp. Here is the dataset https://www.ebi.ac.uk/ena/data/view/SRR5525985

and the command line I'm using

`fastp -i SRR5525985_1.fastq.gz -I SRR5525985_2.fastq.gz -o SRR5525985_1.tr.fastq.gz -O SRR5525985_2.tr.fastq.gz`

fastp version 0.20.0

However, the output is not as expected. The trimmed reads still have a similar dropoff in quality as the untrimmed reads. 

The fastp.html file produced is [here](https://www.dropbox.com/s/qm4a72urrees3ov/fastp.html?dl=0) (dropbox link as github doesn't allow html upload).

I'm probably just reading the options incorrectly, but I expected the output to be high quality (> Q20) to the end of the read. Can you help?

**Comment by sfchen** [comment]
you can add `-q 20 -u 10` to filter out the reads that have >10% bases lower than Q20

**Comment by flashton2003** [comment]
Most read trimmers have an option to just remove the low quality bases from the end of the read, not discard the whole read.

Does fastp have this option?

**Comment by sfchen** [comment]
Yes

# per read cutting by quality score
`fastp` supports per read sliding window cutting by evaluating the mean quality scores in the sliding window. From `v0.19.6`, `fastp` supports 3 different operations, and you enable one or all of them:
* `-5, --cut_front`             move a sliding window from front (5') to tail, drop the bases in the window if its mean quality is below cut_mean_quality, stop otherwise. Default is disabled. The leading N bases are also trimmed. Use `cut_front_window_size` to set the widnow size, and `cut_front_mean_quality` to set the mean quality threshold. If the window size is 1, this is similar as the Trimmomatic `LEADING` method.
* `-3, --cut_tail`              move a sliding window from tail (3') to front, drop the bases in the window if its mean quality is below cut_mean_quality, stop otherwise. Default is disabled. The trailing N bases are also trimmed. Use `cut_tail_window_size` to set the widnow size, and `cut_tail_mean_quality` to set the mean quality threshold. If the window size is 1, this is similar as the Trimmomatic `TRAILING` method.
* `-r, --cut_right`             move a sliding window from front to tail, if meet one window with mean quality < threshold, drop the bases in the window and the right part, and then stop. Use `cut_right_window_size` to set the widnow size, and `cut_right_mean_quality` to set the mean quality threshold.  This is similar as the Trimmomatic `SLIDINGWINDOW` method.


***WARNING: all these three operations will interfere deduplication for SE data, and `--cut_front` or `--cut_right` may also interfere deduplication for PE data. The deduplication algorithms rely on the exact matchment of coordination regions of the grouped reads/pairs.***

If `--cut_right` is enabled, then there is no need to enable `--cut_tail`, since the former is more aggressive. If `--cut_right` is enabled together with `--cut_front`, `--cut_front` will be performed first before `--cut_right` to avoid dropping whole reads due to the low quality starting bases.

Please be noted that `--cut_front` will interfere deduplication for both PE/SE data, and `--cut_tail` will interfere deduplication for SE data, since the deduplication algorithms rely on the exact matchment of coordination regions of the grouped reads/pairs.

If you don't set window size and mean quality threshold for these function respectively, `fastp` will use the values from `-W, --cut_window_size` and `-M, --cut_mean_quality `
