### ISSUE TITLE
umi trimming and deduplication

### ISSUE THREAD

**Issue by HyunjunNam** [OpenGene/fastp#230]
Hi 

I used fastp to trim out umi seqeunce by using the option below,
`fastp -i R1_001.fastq.gz -I R2_001.fastq.gz -o R1_001_umi.fastq.gz -OR2_001_umi.fastq.gz -U --umi_loc=per_read --umi_len=4 --umi_skip=1 -g –Q --adapter_sequence=AGATCGGAAGAGCACACGTCTGAACTCCAGTCA --adapter_sequence_r2=AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT`

De-duplication step was already done by this command? or do I need other step for de-duplication?

Thanks!
HJ

**Comment by sfchen** [comment]
De-duplication from FASTQ  level is not supported by fastp yet.

You can use the BAM file to deduplicate using our other tool gencore https://github.com/OpenGene/gencore

**Comment by juyanmei** [comment]
> De-duplication from FASTQ level is not supported by fastp yet.
> 
> You can use the BAM file to deduplicate using our other tool gencore https://github.com/OpenGene/gencore

Fastp is quite fast, and in some cases，such as metagenomics which is hard to use reference,  I really hope your team can consider adding this feature. As far as I konw,  the other de novo de-duplication software is quite slow to run in metagenomics. 
Otherwise, I am wondering since fastp can identify the duplication, why would not mark it in the sequence header or remove it? I guess maybe the software identify the duplication without considering all reads?

Thanks a lot.

**Comment by sfchen** [comment]
> in version 0.23.0 or later, the read me on github show a function of deduplication with -D, does it means fastp support deduplication from fastq level now? In this case of UMI, can I use both UMI mode -U and deduplication mode -U at the same time? Or I need to do it sequentially, -D then -U, or -U then -D, or deduplication at bam level still prefer?
> 
> thanks
> 
> Ming

Yes, since v0.22.0, fastp supports FASTQ level deduplication. And this feature is compatible with UMI features.
