### ISSUE TITLE
JSON and HTML reports are not generated if a directory is given to --json and --html options

### ISSUE THREAD

**Issue by thbtmntgn** [OpenGene/fastp#40]
It's not really a bug but JSON and HTML reports are not generated if a directory is given to --json and --html options.

I wanted to generate JSON and HTML reports into a specific directory with by default names.
I just gave a directory to --json and --html options but it did not generate the reports.

Maybe it's possible to create --output_directory option (current directory by default) so that we just have to change names with --out1, --out2, --json and --html options. Just an idea 🙂 !

**Comment by sfchen** [comment]
But actually this can be done with --json <dir/fastp.json> --html <dir/fastp.html>.

fastp will throw an error and quit immediately if you specify a existing folder name directly.

**Comment by thbtmntgn** [comment]
Yes yes of course, it was just an idea!

By default names were ok for me so I just try to give a directory to these 2 options and it did not work.

Thanks for your answer!

**Comment by guidohooiveld** [comment]
Likely a stupid question, but since I am struggling with something similar:

How to generate a report if I am using for `<dir>` a character string that is composed of  a directory name + fastq name? Thus e.g. 'samplenumber/fastqname'?

My file setup:
```
workingdir
    seqdata
        - sample1
            --file1.fq.gz
        - sample 2
            --file2.fq.gz


    pfast_out

```
In the working  directory I am executing `fastp` in a loop using:

```
#!/bin/bash
find $PWD/seqdata \( -name '*.fq.gz' -or -name '*.fq' \) -print0 | while read -d $'\0' fn
do
echo "Processing sample ${fn}"
fastp -i ${fn} -p -w 4  --json $PWD/pfast_out/${fn}/fastp.json --html $PWD/pfast_out/${fn}/fastp.html
done
```

directory `pfast_out` (in is created by me before starting `pfast`, but the *.json and *.html files are not generated??

Output names are /workingdir/pfast_out/**seqdata/sample1/file1.fq.gz**/fastp.json, etc.

Since the sub-directory in bold doesn't exists when the files have to be written, the*.json and *.html files are not generated...
How to achieve this?

Thanks for any suggestions!

**Comment by guidohooiveld** [comment]
For the archive; to answer my own question:
after 2nd thought the solution was quite simple: before calling `fastp` I only had to add a command to create a new directory:
`mkdir -p $PWD/fastp_out/${fn}`
That was all....
