### ISSUE TITLE
Compression flag dramatically increases run time

### ISSUE THREAD

**Issue by jasper1918** [OpenGene/fastp#57]
Hi-

I've been using fastp and appreciate the recent updates and features you have been adding.  I noticed the compression is set to 2 by default and want to make sure I control file sizes for our WGS data and reduce the footprint where possible. When I try to set to `-z 6` the run times increases by a factor of 10x or more. Large data effectively never finished. Is this anticipated/expected? 

Perhaps there is something environment related going on and am curious if you can comment on how it is implemented or if their are plans to make the compression more performant.

Thanks!

**Comment by eqhmcow** [comment]
Just a guess -- is this due to running the zlib compression in the main thread? forking a process or adding a thread dedicated to compression may help resolve this issue.

also, at the risk of piling too many feature requests in one ticket, there should be an option to output with no compression at all, so fastq data can be piped around directly (e.g. to another entirely different / custom compression tool)

**Comment by sfchen** [comment]
@eqhmcow if the output file name has no .gz extension, it will not be compressed. So file names like "out.fastq" make plain text output.

Currently the zlib compression of both R1 and R2 are in same thread, and I gonna to separate them to accelerate the compression.

Thank all of you.

**Comment by sfchen** [comment]
@jasper1918 Currently you can output uncompressed data, and then compress them by pgzip once the output is done.

This will eat more disk space, but may a bit faster.

**Comment by sfchen** [comment]
Now, fastp is even faster. The gz writers are moved to individual threads.

`-z 4` is default by now, which is a balance of speed and compression rate.

`-z 6` is still not recommended since gzip compression is too slow

**Comment by KimBioInfoStudio** [comment]
Hello All,
An open soure parallel gzip tools from zlib called "pigz", this tools use multithreads to commpress the file,in order to reduce disk usage ,u can try write no compressed xxx.fq file to a xxx.fifo file then compress it to .gz file with using "pigz".
find more information ----->[http://zlib.net/pigz/](http://zlib.net/pigz/)  .
Thx!
