### ISSUE TITLE
fastp vs AfterQC results

### ISSUE THREAD

**Issue by agroppi** [OpenGene/fastp#68]
I have run AfterQC (0.9.6) and fastp (0.17.0) on the same sample (illumina PE reads) : 
`after.py -1 reads_R1.fastq.gz -2 reads_R2.fastq.gz`
```

fastp \
-w 8 \
-i reads_R1.fastq.gz \
-I reads_R2.fastq.gz \
-o reads_out_L004_R1.fastq.gz \
-O reads_out_L004_R2.fastq.gz \
--json reads_out_L004_R2.fastq.json \
--html reads_out_L004_R2.fastq.html
```

I observed somme difference between the results : numbers of reads ...etc
And thereis a strange value in the fastp results  : 

```
mean length before filtering: | -8bp, -8bp
mean length after filtering: | -15bp, -15bp
```
Screnscaps here attached

Thanks for watching this
![fastp_0 17 0](https://user-images.githubusercontent.com/5609985/41974944-a97414dc-7a19-11e8-9a04-fdfec44a5b1e.JPG)
![afterqc_0 9 6](https://user-images.githubusercontent.com/5609985/41974946-a9913ac6-7a19-11e8-9a1c-4e873e6443e3.JPG)

**Comment by sfchen** [comment]
Sorry, the negative mean length was introduced by an overflow issue.

Please try the latest v0.17.1 from latest code.

**Comment by sfchen** [comment]
The data for fastp and AfterQC are different, right?

**Comment by sfchen** [comment]
The difference of fastp and AfterQC was caused by:
* fastp counts a pair of reads as 2 reads, while AfterQC counts a pair of reads as 1 read.
* fastp use 1000 as 1K, while AfterQC use 1024 as 1K.

I will update AfterQC to keep them consistent.

BTW, AfterQC will not be continued for development since fastp is far far better. So please use fastp other than AfterQC, for any applications.

**Comment by agroppi** [comment]
The input data are the same for AfterQC and fastp.
I'll try fastp 0.17.1
Thanks for your work, fastp in very fast ! (I use 8 threads)

**Comment by agroppi** [comment]
0.17.1 works perfectly and is very fast ! 
Thanks for your work :)
