### ISSUE TITLE
question : activate/desactivate filter types

### ISSUE THREAD

**Issue by Toliman06** [OpenGene/fastp#7]
Hi,

I love your tool and I have a question:
- when using the -W and -M options, is it possible to disable the -q, -u and -n options? I tried a -W -M -Q line, but all the options were disables, including the -W and -Q... (I want to use per the "read cutting by quality options" and disable the "quality filtering options" in the same time)

**Comment by sfchen** [comment]
What's your command?  
`per read cutting by quality` is disabled by default, although you specify `-M` and `-W`.  
You have to set `-5` to enable it on 5' end (front), or set '-3' to enable it on 3' end (tail), or set `-5 -3` to enable both.

**Comment by Toliman06** [comment]
I tried something like this:
`fastp -A -L -w 4 -j ffcf607a-7b70-4e16-a60b-c09197fa1601_report.json -h ffcf607a-7b70-4e16-a60b-c09197fa1601_report.html -W 20 -M 30 -Q \
-i input/ffcf607a-7b70-4e16-a60b-c09197fa1601_1.fastq.gz \
-I input/ffcf607a-7b70-4e16-a60b-c09197fa1601_2.fastq.gz \
-o output/ffcf607a-7b70-4e16-a60b-c09197fa1601_windows_W20M30_1.fastq.gz \
-O output/ffcf607a-7b70-4e16-a60b-c09197fa1601_windows_W20M30_2.fastq.gz`
and nothing was filtered.

Then I removed the -Q, and some reads were filtered according to sliding window on the reads but it also enable the -q -n and -n filtering with the default values, no?

**Comment by sfchen** [comment]
four points:
1, to enable `per read cutting by quality`, you have to set `-5` to enable it on 5' end (front), or set `-3` to enable it on 3' end (tail) . `-W` and `-M` options are only for the settings of this feature but actually not enabling them (I may add a WARNING or ERROR if `-W` or `-M` is specified but neither
 `-5` nor `-3` is enabled). 
2, this feature only cut the reads in the front or end, but will not discard them. So you saw nothing was filtered.
3, this feature has no any conflicts with quality filtering, which can be disabled by `-Q`. 
4, this feature can make reads shorter since it cuts in front or end, so if length filter (can be disabled with `-L`) is enabled, then more reads may be filtered out since they may not pass the length filter.

**Comment by sfchen** [comment]
Could you update? I am going to close this issue

**Comment by Toliman06** [comment]
Thanks for your help.
