### ISSUE TITLE
Write unpaired reads

### ISSUE THREAD

**Issue by jlboat** [OpenGene/fastp#97]
Hello! I've been running fastp tests because I'm considering transitioning my workflow to use it, but as best I can tell, fastp drops unpaired reads. At a minimum, I only get perfectly paired reads in the two output FASTQ files. It's probably not a big deal since the read loss is minor, but I wanted to be sure that the reads are actually being dropped.

To be clear, this is fastp 0.19.4 being run from a Singularity container running Ubuntu.

**Comment by sfchen** [comment]
This feature will be provided in future releases.

**Comment by cfsancas** [comment]
Hello, I am testing fastp and I miss this feature. I would appreciate if it were provided in next versions. Thanks!

**Comment by sfchen** [comment]
Would you guys prefer write unpaired reads to two files separately, or just write them into one single file?

**Comment by sfchen** [comment]
I think two separate files will be better. Agree?

I will implement it soon.

**Comment by cfsancas** [comment]
I agree, thanks!

**Comment by jlboat** [comment]
Yes, two separate files is preferable.

**Comment by sfchen** [comment]
This feature is implemented in fastp v0.19.9 (will be released soon).

# input and output
`fastp` supports both single-end (SE) and paired-end (PE) input/output.
* for SE data, you only have to specify read1 input by `-i` or `--in1`, and specify read1 output by `-o` or `--out1`.
* for PE data, you should also specify read2 input by `-I` or `--in2`, and specify read2 output by `-O` or `--out2`.
* if you don't specify the output file names, no output files will be written, but the QC will still be done for both data before and after filtering.
* the output will be gzip-compressed if its file name ends with `.gz`
## output to STDOUT
`fastp` supports streaming the passing-filter reads to STDOUT, so that it can be passed to other compressors like `bzip2`, or be passed to aligners like `bwa` and `bowtie2`. 
* specify `--stdout` to enable this mode to stream output to STDOUT
* for PE data, the output will be interleaved FASTQ, which means the output will contain records like `record1-R1 -> record1-R2 -> record2-R1 -> record2-R2 -> record3-R1 -> record3-R2 ... ` 
## input from STDIN
* specify `--stdin` if you want to read the STDIN for processing.
* if the STDIN is an interleaved paired-end stream, specify `--interleaved_in` to indicate that.
## store the unpaired reads for PE data
* you can specify `--unpaired1` to store the reads that read1 passes filters but its paired read2 doesn't, as well as `--unpaired2` for unpaired read2.
* `--unpaired1` and `--unpaired2` can be the same, so the unpaired read1/read2 will be written to the same single file.
## store the reads that fail the filters
* give `--failed_out` to specify the file name to store the failed reads.
* if one read failed and is written to `--failed_out`, its `failure reason` will be appended to its read name. For example, `failed_quality_filter`, `failed_too_short` etc.
* for PE data, if unpaired reads are not stored (by giving --unpaired1 or --unpaired2), the failed pair of reads will be put together. If one read passes the filters but its pair doesn't, the `failure reason` will be `paired_read_is_failing`.

**Comment by jlboat** [comment]
Awesome! Thanks.

**Comment by jolespin** [comment]
Hey @sfchen , looking forward to using this in some pipelines!
(1) When will 0.19.9 be released? 
(2) How do the default parameters handle different types of Illumina runs? Does it know which primers to look for etc? 
(3) Have you ever used this to filter reads for amplicon sequencing or is that not advised?

**Comment by sfchen** [comment]
1, 0.19.9 and 0.20.0 have been released for over one month.
2, fastp can detect adapters automatically
3, you can use it for amplicon-seq data
